### PR TITLE
Deleting and modifying collections

### PR DESCRIPTION
**Pull request by sbshaun**
Objectives: (Deleting collection and modifying collections)

On existing collection:

1. ~~Deleting collections~~ (done.)
2. Improve delete collection UI 
3. ~~refactor collections to be dict not array.~~ (done.)
4. ~~add updateCollection API call.~~(done.) 
5. ~~Modifying collection name~~
    - ~~Redux side~~ (done.)
    - ~~Server side~~ (done.) 
6. ~~Making collection private/public Server side~~
    - ~~Redux side~~ (done.)
    - ~~Server side~~ (done.) 

~~On collection creation:~~ (done.)
~~Besides the collection name, create a dropdown for setting the collection private/public~~ (done.)

### CODE REVIEW

**Comment by sbshaun** [comment]
can't delete the collection from the database yet.

**Comment by sbshaun** [comment]
I added a state `selectedCollectionToDelete` in `collectionSlice` in the Redux store. This delete button does the following things: 
1. set `selectedCollectionToDelete` to the selected collection's `collectionId`
2. select all `giffies` under the collection 
3. open a delete confirmation modal




The delete confirmation modal deletes all selected `giffies` (this is working), and it's supposed to delete the collection if there is one selected (not working at the moment). 
```
if (collectionToBeDeleted) {
deleteCollectionsByCollectionId(collectionToBeDeleted);
}
```

**Comment by sbshaun** [comment]
> 

Error cause: a collection can only be deleted when there are no `giffies` related to it. This requires deleting all `giffies` before making a `DELETE` request to the DB for the selected collection.

**Comment by sbshaun** [comment]
found a bug: when going to a different collection page, the `selectedGiffies` isn't cleared.

**Comment by hungnguyen3** [comment]
I modified the backend deleteCollectionById endpoint so that it handles:
- deletion of images
- deletion of giffies
- deletion of the collection

Therefore on the frontend:
- I removed the select all giffies when a collection is selected to be deleted

Ask me for clarification if needed.

**Comment by hungnguyen3** [comment]
Added types to API callers and rewrote in-used API endpoints

**Pull request merged**
